services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=oficina_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  db-test:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=oficina_db_test
    ports:
      - '5434:5432'
    volumes:
      - postgres_test_data:/var/lib/postgresql/data

  #
  api:
    build:
      context: .
    restart: always
    ports:
      - '3001:3001'
    environment:
      DATABASE_URL: 'postgresql://postgres:mysecretpassword@db:5432/oficina_db?schema=public'
      JWT_SECRET: 'SUA_SENHA_SECRETA_SUPER_LONGA_E_ALEATORIA_AQUI_12345'
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npx prisma migrate dev && npm run dev"
  auth-api:
    build:
      context: ../pitstop-auth
    restart: always
    ports:
      - '3002:3002'
    environment:
      DATABASE_URL: 'postgresql://postgres:mysecretpassword@db:5432/oficina_db?schema=auth'
      JWT_SECRET: 'SUA_SENHA_SECRETA_SUPER_LONGA_E_ALEATORIA_AQUI_12345'
    depends_on:
      - db
    volumes:
      - ../pitstop-auth:/app
      - /app/node_modules
    command: sh -c "npx prisma migrate dev && npm run dev"

  tests:
    build:
      context: .
    depends_on:
      - db-test
    environment:
      DATABASE_URL: 'postgresql://postgres:mysecretpassword@db-test:5432/oficina_db_test?schema=public'
      TEST_DATABASE_URL: 'postgresql://postgres:mysecretpassword@db-test:5432/oficina_db_test?schema=public'
      JWT_SECRET: 'test-secret'
      NODE_ENV: 'test'
    volumes:
      - .:/app
      - /app/node_modules
    command: >-
      sh -c "npx dotenv -e .env.test -- prisma migrate deploy --schema prisma/schema.prisma
      && npm run test:e2e"

volumes:
  postgres_data:
  postgres_test_data:
